# Generated by Django 6.0.2 on 2026-02-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste", "0002_coupon_pointstransaction_userpoints_usercoupon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usercoupon",
            options={"ordering": ["-last_updated"]},
        ),
        migrations.RenameField(
            model_name="usercoupon",
            old_name="redeemed_at",
            new_name="first_redeemed_at",
        ),
        migrations.RemoveField(
            model_name="usercoupon",
            name="used",
        ),
        migrations.RemoveField(
            model_name="usercoupon",
            name="used_at",
        ),
        migrations.AddField(
            model_name="usercoupon",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="usercoupon",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
